#!/bin/bash

# Python is an interpreted, interactive, object-oriented programming
# language that combines remarkable power with very clear syntax.
# This is a new version of the language that is incompatible with the
# 2.x line of releases. The language is mostly the same, but many
# details, especially how built-in objects like dictionaries and strings
# work, have changed considerably, and a lot of deprecated features have
# finally been removed. Also, the standard library has been reorganized
# in a few prominent places.

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/python3-3.9.10-x86_64-1.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"


# Add pip to the mix
PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/python-pip-21.3.1-x86_64-2.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"
