#!/bin/bash

# We'll make use of a debian package to install mediainfo
# Therefore we will need deb2tgz

PACKAGE="https://github.com/jbarrett/deb2tgz/archive/refs/tags/0.1.1.tar.gz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

tar xvzf "${PACKAGE##*/}"



# and take care of pre-requisites
PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/binutils-2.37-x86_64-1.txz"

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"

# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/"${PACKAGE_NAME}"* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/



PACKAGE="https://slack.conraid.net/repository/slackware64-current/libzen/libzen-0.4.41-x86_64-1cf.txz"

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"


# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/"${PACKAGE_NAME}"* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/



PACKAGE="https://slack.conraid.net/repository/slackware64-current/libmediainfo/libmediainfo-23.10-x86_64-1cf.txz"

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"


# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/"${PACKAGE_NAME}"* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/



PACKAGE="https://ftp.sotirov-bg.net/pub/contrib/slackware/packages/slackware64-15.0/graphviz-3.0.0-x86_64-1gds.txz"
wget $PACKAGE

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"


# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/"${PACKAGE_NAME}"* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/



# Get the debian mediainfo package
PACKAGE="http://ftp.de.debian.org/debian/pool/main/m/mediainfo/mediainfo_23.04-1_amd64.deb"

wget $PACKAGE


# convert it to Slack package
deb2tgz-0.1.1/deb2tgz "${PACKAGE##*/}"

# and install it
PACKAGE="${PACKAGE##*/}"
upgradepkg --install-new "${PACKAGE/.deb/.tgz}"

# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/"${PACKAGE_NAME}"* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/
