#!/bin/bash

# We'll make use of a debian package to install mediainfo
# Therefore we will need deb2tgz

PACKAGE="https://github.com/jbarrett/deb2tgz/archive/refs/tags/0.1.1.tar.gz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

tar xvzf 0.1.1.tar.gz



# and take care of pre-requuisites
PACKAGE="https://slack.conraid.net/repository/slackware64-current/libzen/libzen-0.4.39-x86_64-1cf.txz"

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"



PACKAGE="https://slack.conraid.net/repository/slackware64-current/libmediainfo/libmediainfo-22.06-x86_64-2cf.txz"

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"



# Get the debian mediainfo package
PACKAGE="http://ftp.de.debian.org/debian/pool/main/m/mediainfo/mediainfo_20.09-1_amd64.deb"

wget $PACKAGE



# convert it to Slack package
deb2tgz-0.1.1/deb2tgz mediainfo_20.09-1_amd64.deb

# and install it
upgradepkg --install-new "mediainfo_20.09-1_amd64.tgz"
