#!/bin/bash

# NCDU is a disk usage analyzer with an ncurses interface, aimed to be run on a
# remote server where you don't have an entire graphical setup, but have
# to do with a simple SSH connection. Ncdu aims to be fast, simple and
# easy to use, and should be able to run in any minimal POSIX-like
# environment with ncurses installed.
#
# now replaced with gncdu which implements NCurses Disk Usage(ncdu) with golang, and is at leaset twice faster as ncdu.

PACKAGE="bastengao/gncdu"
PACKAGE_NAME="gncdu"
PACKAGE_VERSION="$(curl -sL https://api.github.com/repos/bastengao/gncdu/tags | grep -oP '"name": "\K.*?(?=")' | head -n1)"
PACKAGE_VERSION_SHORT=${PACKAGE_VERSION#v}
PACKAGE="https://github.com/${PACKAGE}/releases/download/${PACKAGE_VERSION}/${PACKAGE_NAME}-linux-amd64"

CREATE_ALIAS=true


mkdir /tmp/extras
cd /tmp/extras || exit

wget "$PACKAGE"

PACKAGE="${PACKAGE##*/}"

chmod +x "$PACKAGE"

mv "$PACKAGE" /usr/local/bin/$PACKAGE_NAME

if [[ "${CREATE_ALIAS}" == "false" ]]
  then
    echo "gncdu can be used alongside du"
  else
    alias du='gncdu'
    echo "du can only be used if you first unalias du (to turn off the alias which now points du to gncdu)"
fi
