#!/bin/bash

# NCDU is a disk usage analyzer with an ncurses interface, aimed to be run on a
# remote server where you don't have an entire graphical setup, but have
# to do with a simple SSH connection. Ncdu aims to be fast, simple and
# easy to use, and should be able to run in any minimal POSIX-like
# environment with ncurses installed.

PACKAGE="https://ftp.sotirov-bg.net/pub/contrib/slackware/packages/slackware64-15.0/ncdu-1.18.1-x86_64-1gds.txz"
CREATE_ALIAS=true
FOLLOW_SYMLINKS=true

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"

if [[ "${CREATE_ALIAS}" == "false" ]]
  then
    echo "ncdu can be used alongside du"
  else
    if [[ "${FOLLOW_SYMLINKS}" == "false" ]]
      then
        alias du='ncdu'
      else
        alias du='ncdu --follow-symlinks'
    fi
  echo "du can only be used if you first unalias du (to turn off the alias which now points du to ncdu)"
fi
