#!/bin/bash

# We'll make use of a debian package to install dust
# Therefore we will need deb2tgz

PACKAGE="https://github.com/jbarrett/deb2tgz/archive/refs/tags/0.1.1.tar.gz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

tar xvzf "${PACKAGE##*/}"



# Get the debian dust package
PACKAGE="bootandy/dust"
PACKAGE_NAME="du-dust"
PACKAGE_VERSION="$(curl -sL https://api.github.com/repos/${PACKAGE}/releases/latest | grep -Po '(?<="tag_name": ")[^"]*')"
PACKAGE_VERSION_SHORT=${PACKAGE_VERSION#v}
PACKAGE="https://github.com/${PACKAGE}/releases/download/${PACKAGE_VERSION}/${PACKAGE_NAME}_${PACKAGE_VERSION_SHORT}_amd64.deb"

wget "$PACKAGE"



# convert it to Slack package
deb2tgz-0.1.1/deb2tgz "${PACKAGE##*/}"

# and install it
PACKAGE="${PACKAGE##*/}"
upgradepkg --install-new "${PACKAGE/.deb/.tgz}"

# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/${PACKAGE_NAME}* /boot/extra/previous_versions/
cp "${PACKAGE/.deb/.tgz}" /boot/extra/
