#!/bin/bash

# We'll make use of a debian package to install dust
# Therefore we will need deb2tgz

PACKAGE="https://github.com/jbarrett/deb2tgz/archive/refs/tags/0.1.1.tar.gz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

tar xvzf "${PACKAGE##*/}"



# Get the debian mediainfo package
PACKAGE="https://github.com/bootandy/dust/releases/download/v0.8.6/du-dust_0.8.6_amd64.deb"

wget $PACKAGE



# convert it to Slack package
deb2tgz-0.1.1/deb2tgz "${PACKAGE##*/}"

# and install it
PACKAGE="${PACKAGE##*/}"
upgradepkg --install-new "${PACKAGE/.deb/.tgz}"
