#!/bin/bash

# Python is an interpreted, interactive, object-oriented programming
# language that combines remarkable power with very clear syntax.
# Python's basic power can be extended with your own modules written in
# C or C++. Python is also adaptable as an extension language for
# existing applications.

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/python2-2.7.18-x86_64-4.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"
