#!/bin/bash
# Start the Management Utility
/usr/local/sbin/emhttp -p 81 &

sed -i -e 's/^telnet/#telnet/' /etc/inetd.conf
/etc/rc.d/rc.inetd restart

# do not touch above this line (setup by Lime)

# reusable on any box

cat /boot/config/.my_bashrc >> /root/.bashrc
cat /boot/config/.my_bash_aliases >> /root/.bash_aliases
cat /boot/config/.my_bash_functions >> /root/.bash_functions
cat /boot/config/.my_bash_prompt >> /root/.bash_prompt
cat /boot/config/.my_bash_profile >> /root/.bash_profile

# reusable on THIS box
cat /boot/config/.my_machine_aliases >> /root/.bash_aliases
