#!/bin/bash

# BorgBackup (short: Borg) is a deduplicating backup program. 
# Optionally, it supports compression and authenticated encryption.

PACKAGE="https://github.com/borgbackup/borg/releases/download/1.2.2/borg-linux64"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

chmod +x "${PACKAGE##*/}"

mv "${PACKAGE##*/}" /usr/local/sbin/borg
