#!/bin/bash

# Python is an interpreted, interactive, object-oriented programming
# language that combines remarkable power with very clear syntax.
# This is a new version of the language that is incompatible with the
# 2.x line of releases. The language is mostly the same, but many
# details, especially how built-in objects like dictionaries and strings
# work, have changed considerably, and a lot of deprecated features have
# finally been removed. Also, the standard library has been reorganized
# in a few prominent places.

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/python2-2.7.18-x86_64-4.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"
