#!/bin/bash

# ExifTool is a platform-independent Perl library (Image::ExifTool)
# plus a command-line application (exiftool) for reading, writing,
# and editing meta information in image, audio, and video files.
# ExifTool supports many different types of metadata including EXIF,
# GPS, IPTC, XMP, JFIF, GeoTIFF, ICC Profile, Photoshop IRB, AFCP,
# FlashPix, AFCP, and ID3, and maker notes of many digital cameras.


PACKAGE="exiftool/exiftool"
PACKAGE_NAME="exiftool"
PACKAGE_VERSION="$(curl -sL https://api.github.com/repos/${PACKAGE}/tags | grep -Po '"name": "\K.*?(?=")' | head -n1)"
PACKAGE_VERSION_SHORT=${PACKAGE_VERSION#v}
PACKAGE="https://slack.conraid.net/repository/slackware64-current/${PACKAGE}-${PACKAGE_VERSION_SHORT}-x86_64-1cf.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget "$PACKAGE"

PACKAGE="${PACKAGE##*/}"
upgradepkg --install-new "${PACKAGE##*/}"

# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/${PACKAGE_NAME}* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/
