#!/bin/bash

# ATOP is an advanced interactive monitor for Linux-systems
# to view the load on system-level and process-level.
# atop was wtitten and is maintained by Gerlof Langeveld of
# AT Consultancy bv, Nijmegen, The Netherlands

PACKAGE="Atoptool/atop"
PACKAGE_NAME="atop"
PACKAGE_VERSION="$(curl -sL https://api.github.com/repos/${PACKAGE}/tags | grep -Po '"name": "\K.*?(?=")' | head -n1)"
PACKAGE_VERSION_SHORT=${PACKAGE_VERSION#v}
PACKAGE="https://slack.conraid.net/repository/slackware64-current/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION_SHORT}-x86_64-1cf.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

PACKAGE="${PACKAGE##*/}"
upgradepkg --install-new "${PACKAGE}"

# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/${PACKAGE_NAME}* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/
