#!/bin/bash

# ATOP is an advanced interactive monitor for Linux-systems
# to view the load on system-level and process-level.
# atop was wtitten and is maintained by Gerlof Langeveld of
# AT Consultancy bv, Nijmegen, The Netherlands

PACKAGE="https://slack.conraid.net/repository/slackware64-current/atop/atop-2.9.0-x86_64-1cf.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"
