#!/bin/bash

# # screen (screen manager with VT100/ANSI terminal emulation)
#
# Screen is a full-screen window manager that multiplexes a physical
# terminal between several processes (typically interactive shells).
# Each virtual terminal provides the functions of a DEC VT100 terminal
# and several control functions from the ISO 6492 (ECMA 48, ANSI X3.64)
# and ISO 2022 standards (e.g. insert/delete line and support for
# multiple character sets). There is a scrollback history buffer for
# each virtual terminal and a copy-and-paste mechanism that allows
# moving text regions between windows.

# see http://aperiodic.net/screen/quick_reference

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/ap/screen-4.9.0-x86_64-1.txz"
PACKAGE_NAME="screen"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

PACKAGE="${PACKAGE##*/}"
upgradepkg --install-new "${PACKAGE}"

# and make it available for use at boot next time (i.e. before array is strated)
mv /boot/extra/${PACKAGE_NAME}* /boot/extra/previous_versions/
cp "${PACKAGE}" /boot/extra/
