#!/bin/bash

# iotop is a Python program with a top-like UI used to show of behalf of which process is the I/O going on.

PACKAGE="https://slack.conraid.net/repository/slackware64-current/fdupes/fdupes-2.2.1-x86_64-1cf.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"
