#!/bin/bash

# iperf is a tool for active measurements of the maximum achievable
# bandwidth on IP networks. It supports tuning of various parameters
# related to timing, protocols, and buffers. For each test it reports
# the bandwidth, loss, and other parameters.
# Iperf3 is a redesign of an original version developed at NLANR/DAST
#
# Usage: iperf3 [-s|-c host] [options]
#        iperf3 [-h|--help] [-v|--version

PACKAGE="https://slack.conraid.net/repository/slackware64-current/iperf3/iperf3-3.11-x86_64-1cf.txz"

mkdir /tmp/extras
cd /tmp/extras || exit

wget $PACKAGE

upgradepkg --install-new "${PACKAGE##*/}"
