#!/bin/bash

# These are packages that have been used at one time or another when building/installing other packages

mkdir /tmp/extras
cd /tmp/extras || exit


PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/autoconf-2.69-noarch-4.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/automake-1.16.2-noarch-4.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/gcc-11.2.0-x86_64-2.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/libtool-2.4.6-x86_64-18.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/m4-1.4.19-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"
