#!/bin/bash

# These are packages that have been used at one time or another when building/installing other packages

mkdir /tmp/extras
cd /tmp/extras || exit


PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/autoconf-2.69-noarch-4.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/automake-1.16.2-noarch-4.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/binutils-2.37-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/cmake-3.21.4-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/flex-2.6.4-x86_64-5.txz@
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/l/gc-8.0.6-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/gcc-11.2.0-x86_64-2.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/gcc-g++-11.2.0-x86_64-2.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/l/glib-1.2.10-x86_64-9.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/l/glib2-2.70.3-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/l/glibc-2.33-x86_64-5.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/n/gpgme-1.16.0-x86_64-3.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"
  
PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/guile-3.0.7-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://mirrors.slackware.com/slackware/slackware64-15.0/slackware64/d/kernel-headers-5.15.19-x86-2.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/n/libgpg-error-1.44-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/libtool-2.4.6-x86_64-18.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/m4-1.4.19-x86_64-1.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/make-4.3-x86_64-3.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/d/pkg-config-0.29.2-x86_64-4.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"

PACKAGE="https://slackware.uk/slackware/slackware64-15.0/slackware64/l/zlib-1.2.11-x86_64-4.txz"
wget $PACKAGE
upgradepkg --install-new "${PACKAGE##*/}"
